export function escape(commands: any): string;
export function chomp(s: any): any;
export function execSSH(sshHost: any, cmd: any, env: any, options: any): Promise<any>;
export function spawnSSH(sshHost: any, cmd: any, sshOptions: any, options: any): any;
export function spawnStd(cmd: any, args: any, options: any): Promise<any>;
export function spawnStdBash(cmd: any, options: any): any;
export function exec(cmd: any, options: any): Promise<any>;
export function realpath(s: any): Promise<any>;
export function cmdDir(): any;
export function cmdRel(path: any): any;
export function ls(dir: any): Promise<any>;
export function exists(path: any): Promise<boolean>;
export function cp(src: any, dest: any): void;
export function cp_rf(src: any, dest: any): Promise<void>;
export function cat(f: any): Promise<any>;
export function cat_silent(f: any): Promise<any>;
export function cat_bin(f: any): Promise<any>;
export function write(f: any, content: any): Promise<any>;
export function write_f(f: any, content: any): Promise<void>;
export function rm(f: any): Promise<void>;
export function rm_rf(f: any): Promise<void>;
export function isFile(f: any): Promise<any>;
export function isDir(d: any): Promise<any>;
export function mkdir_p(path: any): Promise<void>;
export function stat(path: any): Promise<any>;
export function touch(file: any): Promise<void>;
export function removeSuffix(name: any, suffix: any): any;
export function mktemp(prefix: any): Promise<any>;
export function withinTemp(prefix: any, callback: any): any;
export function writeMapping(dir: any, mapping: any): Promise<void>;
export function wait(n: any): any;
export function sleep(n: any): any;
export function error(msg: any): void;
export function md5(s: any): any;
export { dirname };
