export function randInt(low: any, high: any): any;
export function randItem(array: any): any;
export function map(obj: any, f: any): any[];
export function mapToArray(obj: any, f: any): any[];
export function values(obj: any): any[];
export function keyValues(obj: any): any[];
export function remap(obj: any, f: any): {};
export function keyValueRemap(obj: any, f: any): {};
export function valueRemap(obj: any, f: any): {};
export function remapValue(obj: any, f: any): {};
export function range(n: any): any;
export function methods(o: any, includePrivate: any): {};
