export function joinByOneSep(a: any, b: any, sep: any): any;
export function countLines(s: any): number;
export function indentLines(s: any, prefix: any): any;
export function removeSuiffx(s: any, suffix: any): any;
export function format(format: any, ...args: any[]): any;
export function capitalize(s: any): any;
export function interpolation(template: any, ...ctx: any[]): any;
export function flattenSplit(s: any, separator: string, options: any): any[];
export function escapeShell(word: any): string;
export function escapeHTMLText(s: any): any;
export function isEmpty(v: any): boolean;
export function isNotEmpty(v: any): boolean;
export function isNumeric(v: any, positive: any): boolean;
export function isNumericString(s: any, positive: any): boolean;
export function isPositive(v: any): boolean;
